[project]
name = "chat-snake"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "pytest>=8.4.1",
    "python-levenshtein>=0.27.1",
    "streamlit>=1.46.1",
]
